import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ProvidersWrapper } from "./providers-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={`${inter.className}`} cz-shortcut-listen="true">
          <ProvidersWrapper>{children}</ProvidersWrapper>
      </body>
    </html>
  );
}
